### PR TITLE
#161348753 Users should be able Signup/Register to Authors Haven

### PR DESCRIPTION
**Pull request by brucemakallan**
#### What does this PR do?
Provides a form for user registration
#### Description of Task to be completed?
 - A user is able to signup
 - Error messages and messages for successful registration are displayed
 - Validate user data before registering
#### How should this be manually tested?
- Go to `/signup`
- Provide `username`, `email`, and `password` details then click "Sign Up"
#### Any background context you want to provide?
You need to verify your email after signup
#### What are the relevant pivotal tracker stories?
[#161348753](https://www.pivotaltracker.com/story/show/161348753)

### CODE REVIEW

**Review by judeinno — COMMENTED** [review]
Work on the code climate complaints, please.

**Review by dnuwa — COMMENTED** [review]
@brucemakallan could we please have a folder for the actions and their tests inside the same folder. e.g `SiginupActions with signupAction.js and signupAction.test.js`

**Review by judeinno — APPROVED** [review]

**Review by RachaelNantale — APPROVED** [review]
Good work destructuring the code and and maintainability

**Comment by tibetegya** [comment]
@brucemakallan Your branch name is too long please read the engineering best practices very carefully, It recommends not more than three words in the branch name.

**Comment by tibetegya** [comment]
screen shot 2018-12-06 at 16 06 55
remove the console logs

**Pull request closed without merging**
